[package]
name = "script"
edition.workspace = true
version.workspace = true

[dependencies]
clap = { workspace = true }
solana-client = { workspace = true }
solana-cli-config = { workspace = true }
solana-sdk = { workspace = true, features = ["default"] }
